language: php
php:
  - 7.0
  - 7.1
  - 7.2
script:
  - composer install
  - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - php coverage.php clover.xml 30
after_success:
  - travis_retry php vendor/bin/php-coveralls -v
